routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LogActivityController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductSaleController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\TicketSaleController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::group(['namespace' => 'Auth'], function() {
    Route::get('login', [LoginController::class,'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class,'login'])->name('login.store');
    Route::post('logout', [LoginController::class,'logout'])->name('logout')->middleware('auth');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function() { return redirect()->route('dashboard'); });
    Route::get('dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
    Route::get('dashboard-ticket', [DashboardController::class, 'ticket'])->name('dashboard.ticket');
    Route::get('dashboard-store', [DashboardController::class, 'store'])->name('dashboard.store');
    
    Route::resource('tickets', TicketController::class)->only(['destroy']);
    Route::get('tickets-valid', [TicketController::class, 'valid'])->name('ticket.valid');
    Route::get('tickets-invalid', [TicketController::class, 'invalid'])->name('ticket.invalid');
    Route::post('ticket-import', [TicketController::class, 'import'])->name('ticket.import');

    Route::resource('ticket-sales', TicketSaleController::class)->only(['index','destroy']);

    Route::resource('products', ProductController::class)->except(['edit']);
    Route::get('product-barcode/{code}', [ProductController::class, 'print_barcode'])->name('product.print-barcode');
    Route::post('export/products', [ProductController::class, 'export'])->name('export.products');

    Route::resource('product-sales', ProductSaleController::class)->only(['index', 'show', 'destroy']);

    Route::get('transaction/synchronized-data', [LogActivityController::class, 'synchronized_data'])->name('transaction.synchronized-data');
    Route::resource('transaction', TransactionController::class)->only(['index', 'store', 'show']);
    
    Route::resource('users', UserController::class)->only(['index', 'store', 'destroy']);
    Route::post('user/change-role/{user}', [UserController::class, 'changeRole'])->name('user.change-role');
    Route::post('user/change-password/{user}', [UserController::class, 'changePassword'])->name('user.change-password');
    
    Route::get('report-tickets', [ReportController::class, 'reportTickets'])->name('report.tickets');
    Route::post('report-tickets/export', [ReportController::class, 'exportTickets'])->name('report.export.tickets');
    Route::get('report-store', [ReportController::class, 'reportStore'])->name('report.store');
    Route::post('report-store/export', [ReportController::class, 'exportStore'])->name('report.export.store');

    Route::resource('log-activities', LogActivityController::class)->only(['index', 'destroy']);
});

Route::get('customer-display/{type}', [Controller::class, 'customer_display'])->name('customer.display');
Route::get('product-display/{name}/{price}', [ProductController::class, 'display_product'])->name('product.display');

app/Models/Ticket.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ticket extends Model {

    use HasFactory;

    const ID = 'id';
    const TYPE_ID = 'type_id';    
    const BARCODE = 'barcode';
    const IS_VALID = 'is_valid';

    protected $guarded = [];

    protected function serializeDate(DateTimeInterface $date) {
        return $date->format('Y-m-d H:i:s');
    }

    function type() {
        return $this->belongsTo(TicketType::class);
    }

    function item() {
        return $this->hasOne(TicketSaleItem::class);
    }

    function scopeValidate($query, $state = true) {
        $query->where(Self::IS_VALID, $state);
    }
}

app/Models/TicketType.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TicketType extends Model {

    use HasFactory;

    const IMAGE_PATH = 'ticket/';

    const ID = 'id';
    const NAME = 'name';
    const PRICE = 'price';
    const IMAGE = 'image';
    const INVENTORY = 'inventory';

    const TICKET_FREE = 1;
    const TICKET_DOMESTIC = 2;
    const TICKET_NATIONAL = 3;
    const TICKET_INTERNATIONAL = 4;

    protected $guarded = [];

    protected function serializeDate(DateTimeInterface $date) {
        return $date->format('Y-m-d H:i:s');
    }

    function tickets() {
        return $this->hasMany(Ticket::class, Ticket::TYPE_ID);
    }

    function getImageAttribute($value) {
        return asset('assets/img/'.Self::IMAGE_PATH.$value);
    }

    function decrementInventory($qty = 1) {
        $inventory = $this->attributes[Self::INVENTORY] - $qty;
        $this->update([Self::INVENTORY => $inventory]);
        return;
    }

    function incrementInventory($qty = 1) {
        $inventory = $this->attributes[Self::INVENTORY] + $qty;
        $this->update([Self::INVENTORY => $inventory]);
        return;
    }
}

app/Http/Controllers/Api/V1/Ticket/TicketController.php
<?php

namespace App\Http\Controllers\Api\V1\Ticket;

use App\Http\Controllers\Controller;
use App\Http\Requests\RoleActivityRequest;
use App\Models\Ticket;
use App\Models\TicketSale;
use App\Models\TicketSaleItem;
use App\Models\TicketType;
use App\Models\TypePayment;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use charlieuki\ReceiptPrinter\ReceiptPrinter as ReceiptPrinter;
use Illuminate\Http\Request;

class TicketController extends Controller {
    
    function get_type_ticket() {
        $tickets = TicketType::get();

        return $this->response_success('Data seluruh tiket berhasil didapatkan.', $tickets);
    }

    function get_type_payment() {
        $types = TypePayment::get();

        return $this->response_success('Data jenis pembayaran berhasil didapatkan.', $types);
    }

    function store_transaction(RoleActivityRequest $request) {
        $validator = Validator::make($request->all(), [
            TicketSale::PAYMENT_ID => 'required|numeric',
            TicketSale::CUST_NAME => 'nullable',
            TicketSale::DISCOUNT => 'nullable|numeric',
            TicketSale::FINAL_AMOUNT => 'required|numeric',
            TicketSale::TOTAL_PRICE => 'required|numeric',
            TicketSale::NOTE => 'nullable',
            'tickets' => 'required|array|min:1',
        ]);

        if ($validator->fails()) 
            return $this->response_error('Terdapat Kesalahan', $validator->errors(), 400);

        DB::beginTransaction();

        try {
            $payload = $request->except('tickets', 'device');
            $payload[TicketSale::USER_ID] = auth()->id();
            $payload[TicketSale::DISCOUNT] = $payload[TicketSale::DISCOUNT] / 100 * $payload[TicketSale::TOTAL_PRICE];
            $sale = TicketSale::create($payload);

            $tickets = $request->input('tickets');
            $total_price = 0;
    
            foreach ($tickets as $key => $value) {
                // $tickets = Ticket::where(Ticket::TYPE_ID, $value['type_id'])->validate()->count();

                // if ($tickets < $value['qty']) {
                //     DB::rollBack();
                //     return $this->response_error('Jumlah tiket telah habis.', null, 400);
                // }

                // $total_price += $tickets->price * $value['qty'];

                $type = TicketType::find($value['type_id']);
                TicketSaleItem::create([
                    TicketSaleItem::SALE_ID => $sale->id,
                    TicketSaleItem::TICKET_TYPE_ID => $value['type_id'],
                    TicketSaleItem::NAME => $type->name,
                    TicketSaleItem::PRICE => $type->price,
                    TicketSaleItem::QTY => $value['qty'],
                ]);

                if (TicketType::find($value['type_id'])->inventory >= $value['qty']) 
                    TicketType::find($value['type_id'])->decrementInventory($value['qty']);
            }
    
            // if ($total_price != $request->input(TicketSale::TOTAL_PRICE)) {
            //     DB::rollBack();
            //     return $this->response_error('Total harga mengalami perubahan.', null, 400);
            // }

            $activity['device'] = $request->input('device');
            $activity['role'] = $request->input('role');
            $activity['data'] = array_merge(['transaction_id' => $sale->id],$request->except('device','role','tickets'));
            $this->save_activity('Penjualan tiket', $activity);

            DB::commit();
            return $this->response_success('Data transaksi berhasil di proses.', $sale);
        } catch (\Throwable $th) {
            DB::rollBack();
            return $this->response_error($th->getMessage(), null, 403);
        }
    }

    function list_transaction_history(Request $request) {
        $histories = TicketSale::withSum('items', TicketSaleItem::QTY)
                    ->when($request->input('start_date'), function ($query) use ($request) {
                        $query->whereDate(TicketSaleItem::CREATED_AT, '>=', $request->input('start_date'));
                    })
                    ->when($request->input('end_date'), function ($query) use ($request) {
                        $query->whereDate(TicketSaleItem::CREATED_AT, '<=', $request->input('end_date'));
                    })
                    ->where(TicketSale::USER_ID, $request->user()->id)->get();

        return $this->response_success('Data penjualan tiket.', $histories);
    }

    function detail_transaction(Request $request) {
        $validator = Validator::make($request->all(), [
            TicketSale::ID => 'required'
        ]);

        if ($validator->fails())
            return $this->response_error('Terdapat Kesalahan Formulir Tiket', $validator->errors(), 400);

        $sale = TicketSale::with('items')->find($request->input(TicketSale::ID));

        if ($sale == null)
            return $this->response_error('Data penjualan tiket tidak ditemukan.',null, 404);

        return $this->response_success('Data penjualan tiket.', $sale);
    }

    function scan_barcode(Request $request) { 
        $validator = Validator::make($request->all(), [
            Ticket::BARCODE => 'required'
        ]);

        if ($validator->fails())
            return $this->response_error('Terdapat Kesalahan', $validator->errors(), 400);

        $ticket = Ticket::where(Ticket::BARCODE, $request->input(Ticket::BARCODE))->first();

        if ($ticket == null)
            return $this->response_error('Data Barcode Tidak Ditemukan.', null, 404);

        if (!$ticket->is_valid) 
            return $this->response_error('Tiket sudah digunakan atau telah dipindai.', null, 401);

        $ticket->update([ Ticket::IS_VALID => false ]);

        return $this->response_success('Tiket berhasil dipindai.', null);
    }

    function list_entrance_history(Request $request) { 
        $histories = Ticket::validate(false)
                    ->when($request->input('start_date'), function ($query) use ($request) {
                        $query->whereDate(TicketSaleItem::UPDATED_AT, '>=', $request->input('start_date'));
                    })
                    ->when($request->input('end_date'), function ($query) use ($request) {
                        $query->whereDate(TicketSaleItem::UPDATED_AT, '<=', $request->input('end_date'));
                    })
                    // ->whereDate(TicketSaleItem::UPDATED_AT, '>=', $request->input('start_date'))
                    // ->whereDate(TicketSaleItem::UPDATED_AT, '<=', $request->input('end_date'))
                    ->latest(Ticket::UPDATED_AT)->get();

        return $this->response_success('Data penjualan tiket.', $histories);
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Imports\TicketImport;
use App\Models\Ticket;
use App\Models\TicketType;
use Illuminate\Http\Request;
use Excel;
use DataTables;
use Illuminate\Database\QueryException;

class TicketController extends Controller {

    function __construct() {
        $this->middleware('permission:view-tickets')->only('index');
        $this->middleware('permission:delete-tickets')->only('destroy');
        $this->middleware('permission:import-tickets')->only('import');
    }

    public function valid() {
        if (request()->ajax()) {
            $tickets = Ticket::with(['type' => function($q) {
                $q->select(TicketType::ID, TicketType::NAME, TicketType::PRICE);
            }])->where(Ticket::IS_VALID, 1);
            
            return Datatables::eloquent($tickets)
                ->addIndexColumn()
                ->addColumn('type_name', function (Ticket $ticket) {
                    return $ticket->type->name;
                })
                ->addColumn('price', function(Ticket $ticket) {
                    return 'Rp. '. number_format($ticket->type->price, 0, '', '.');
                })
                ->addColumn('status', function($row) {
                    return '<span class="badge badge-sm badge-success"> Valid </span>';
                })
                ->addColumn('action', function($row){
                    return '<button class="btn btn-sm btn-danger" onclick="deleteTicket('.$row->id.')"><i class="fa fa-trash mr-1"></i> Hapus</button>';
                })
                ->rawColumns(["type_name",'status','action'])
                ->blacklist(['DT_RowIndex','action'])
                ->toJson();
        }
        return view('ticket.valid');
    }

    public function invalid() {
        if (request()->ajax()) {
            $tickets = Ticket::with(['type' => function($q) {
                $q->select(TicketType::ID, TicketType::NAME, TicketType::PRICE);
            }])->where(Ticket::IS_VALID, 0);

            return Datatables::eloquent($tickets)
                ->addIndexColumn()
                ->addColumn('type_name', function (Ticket $ticket) {
                    return $ticket->type->name;
                })
                ->addColumn('price', function(Ticket $ticket) {
                    return 'Rp. '. number_format($ticket->type->price, 0, '', '.');
                })
                ->addColumn('status', function($row) {
                    return '<span class="badge badge-sm badge-dark"> Invalid </span>';
                })
                ->addColumn('action', function($row){
                    return '<button class="btn btn-sm btn-danger" onclick="deleteTicket('.$row->id.')"><i class="fa fa-trash mr-1"></i> Hapus</button>';
                })
                ->rawColumns(["type_name",'action'])
                ->escapeColumns('status')
                ->blacklist(['DT_RowIndex','action'])
                ->toJson();
        }
        return view('ticket.invalid');
    }

    public function destroy(Ticket $ticket) {
        $ticket->delete();

        return response(['status' => true, 'message' => 'Data Tiket berhasil terhapus']);
    }

    function import(Request $request) {
        try {
            Excel::import(new TicketImport, $request->file('file')->store('temp'));
            return redirect()->back()->with(['message'=> 'Data berhasil di import', 'status' => 'success']);
        } catch (QueryException $q) {
            $errorCode = $q->errorInfo[1];
            if($errorCode == '1062'){
                return redirect()->back()->with(['message'=> 'Data barcode terdapat duplikasi.', 'status' => 'error']);
            }
            return redirect()->back()->with(['message'=> $q->getMessage(), 'status' => 'error']);
        }
    }
}

resources/views/ticket/invalid.blade.php
@extends('layout.main')
@section('title','Daftar Tiket Yang Invalid')

@section('content')
<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card card-warning">
                {{-- <div class="card-header">
                    <h4>Basic DataTables</h4>
                </div> --}}
                <div class="card-body">
                    <div class="table-responsive" >
                        <table class="table table-striped" id="table-tickets" style="width: 100%">
                            <thead>
                                <tr>
                                    <th class="text-center">No.</th>
                                    <th>Jenis Tiket</th>
                                    <th>Barcode</th>
                                    <th>Harga @</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center">Dibuat</th>
                                    <th class="text-center">Diperbarui</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal -->
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Konfirmasi Hapus</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                Apakah anda yakin ingin menghapus Tiket ini ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger" id="btn-delete-ticket">Hapus</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('addons-style')
<link rel="stylesheet" href="{{ asset('assets/bundles/datatables/datatables.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/bundles/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css') }}">
@endpush

@push('addons-script')
<!-- JS Libraies -->
<script src="{{ asset('assets/bundles/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('assets/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/bundles/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Page Specific JS File -->
<script src="{{ asset('assets/js/page/datatables.js') }}"></script>

<script>
    var ticket_id = 1;

    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': "{{ csrf_token() }}"
            }
        })
        let dt_tickets = $('#table-tickets').DataTable( {
            processing: true,
            serverSide: true,
            paging:true,
            ajax: "{!! url()->current() !!}",
            pageLength: 50,
            order: [[5, 'asc']],
            scrollY: 600,
            scrollCollapse: true,
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex', sClass: "text-center", orderable: false, searchable: false, bSortable: false},
                {data: 'type_name', name: 'type.name'},
                {data: 'barcode', name: 'barcode'},
                {data: 'price', name: 'type.price', sClass: "text-right", type: 'natural'},
                {data: 'status', name: 'is_valid',sClass: "text-center"},
                {data: 'created_at', name: 'created_at', sClass: "text-center"},
                {data: 'updated_at', name: 'updated_at', sClass: "text-center"},
                {data: 'action', name: 'action', sClass: "text-center", orderable: false, searchable: false, bSortable: false},
            ],
        });
        dt_tickets.on( 'order.dt search.dt', function () {
            dt_tickets.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                cell.innerHTML = i+1;
            } );
        } ).draw();

        $('#btn-delete-ticket').click(function (e) { 
            e.preventDefault();
            let url_delete = "{{ route('tickets.destroy', ':id') }}";

            $.ajax({
                type: "DELETE",
                url: url_delete.replace(':id', ticket_id),
                success: function (response) {
                    if (response.status) {
                        dt_tickets.ajax.reload(function () {
                            $('#modal-delete').modal('hide');
                            showAlert('success',response.message,'Berhasil')
                        }, false);
                    }
                },
            });
        });
    });

    function deleteTicket(id) {
        ticket_id = id;
        $('#modal-delete').modal('show');
    }
</script>
@endpush

resources/views/ticket/valid.blade.php
@extends('layout.main')
@section('title','Daftar Tiket Yang Valid')

@section('content')
<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card card-warning">
                {{-- <div class="card-header">
                    <h4>Basic DataTables</h4>
                </div> --}}
                <div class="card-body">
                    <form action="{{ route('ticket.import') }}" method="POST" id="form-import" style="display: none" enctype='multipart/form-data'>
                        @csrf
                        <input type="file" id="input-file-import" name="file" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
                    </form>
                    <div class="table-responsive" >
                        <table class="table table-striped" id="table-tickets" style="width: 100%">
                            <thead>
                                <tr>
                                    <th class="text-center">No.</th>
                                    <th>Jenis Tiket</th>
                                    <th>Barcode</th>
                                    <th>Harga @</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center">Dibuat</th>
                                    <th class="text-center">Diperbarui</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal -->
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Konfirmasi Hapus</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                Apakah anda yakin ingin menghapus Tiket ini ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger" id="btn-delete-ticket">Hapus</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('addons-style')
<link rel="stylesheet" href="{{ asset('assets/bundles/datatables/datatables.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/bundles/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css') }}">
@endpush

@push('addons-script')
<!-- JS Libraies -->
<script src="{{ asset('assets/bundles/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('assets/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/bundles/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Page Specific JS File -->
<script src="{{ asset('assets/js/page/datatables.js') }}"></script>

<script>
    var ticket_id = 1;

    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': "{{ csrf_token() }}"
            }
        })
        let dt_tickets = $('#table-tickets').DataTable( {
            processing: true,
            serverSide: true,
            paging:true,
            ajax: "{!! url()->current() !!}",
            pageLength: 50,
            order: [[5, 'asc']],
            scrollY: 600,
            scrollCollapse: true,
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex', sClass: "text-center", orderable: false, searchable: false, bSortable: false},
                {data: 'type_name', name: 'type.name'},
                {data: 'barcode', name: 'barcode'},
                {data: 'price', name: 'type.price', sClass: "text-right", type: 'natural'},
                {data: 'status', name: 'is_valid',sClass: "text-center"},
                {data: 'created_at', name: 'created_at', sClass: "text-center"},
                {data: 'updated_at', name: 'updated_at', sClass: "text-center"},
                {data: 'action', name: 'action', sClass: "text-center", orderable: false, searchable: false, bSortable: false},
            ],
            initComplete: function(){
                $("#table-tickets_filter").parent().after(`
                    <div class="col-12 col-md-4 text-center text-md-right">
                        <button class="btn btn-rounded btn-warning mb-2" onclick="importTickets()"><i class="fa fa-file mr-2"></i> Import Barcode Tiket</button>
                    </div>
                `);
                $("#table-tickets_length").parent().addClass('col-12 col-sm-6 col-md-4').removeClass('col-sm-12 col-md-6')
                $("#table-tickets_filter").css('text-align', 'center');
                $("#table-tickets_filter").parent().addClass('col-12 col-sm-6 col-md-4').removeClass('col-sm-12 col-md-6')
            }   
        });
        dt_tickets.on( 'order.dt search.dt', function () {
            dt_tickets.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                cell.innerHTML = i+1;
            } );
        } ).draw();

        $('#btn-delete-ticket').click(function (e) { 
            e.preventDefault();
            let url_delete = "{{ route('tickets.destroy', ':id') }}";

            $.ajax({
                type: "DELETE",
                url: url_delete.replace(':id', ticket_id),
                success: function (response) {
                    if (response.status) {
                        dt_tickets.ajax.reload(function () {
                            $('#modal-delete').modal('hide');
                            showAlert('success',response.message,'Berhasil')
                        }, false);
                    }
                },
            });
        });
    });

    function importTickets() {
        $('#input-file-import').click();
    }

    $('#input-file-import').on('change', function(){ 
        if ($(this).get(0).files.length != 0) {
            $( "#form-import" ).submit();
        }
    });

    function deleteTicket(id) {
        ticket_id = id;
        $('#modal-delete').modal('show');
    }
</script>
@endpush