routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LogActivityController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductSaleController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\TicketSaleController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::group(['namespace' => 'Auth'], function() {
    Route::get('login', [LoginController::class,'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class,'login'])->name('login.store');
    Route::post('logout', [LoginController::class,'logout'])->name('logout')->middleware('auth');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function() { return redirect()->route('dashboard'); });
    Route::get('dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
    Route::get('dashboard-ticket', [DashboardController::class, 'ticket'])->name('dashboard.ticket');
    Route::get('dashboard-store', [DashboardController::class, 'store'])->name('dashboard.store');
    
    Route::resource('tickets', TicketController::class)->only(['destroy']);
    Route::get('tickets-valid', [TicketController::class, 'valid'])->name('ticket.valid');
    Route::get('tickets-invalid', [TicketController::class, 'invalid'])->name('ticket.invalid');
    Route::post('ticket-import', [TicketController::class, 'import'])->name('ticket.import');

    Route::resource('ticket-sales', TicketSaleController::class)->only(['index','destroy']);

    Route::resource('products', ProductController::class)->except(['edit']);
    Route::get('product-barcode/{code}', [ProductController::class, 'print_barcode'])->name('product.print-barcode');
    Route::post('export/products', [ProductController::class, 'export'])->name('export.products');

    Route::resource('product-sales', ProductSaleController::class)->only(['index', 'show', 'destroy']);

    Route::get('transaction/synchronized-data', [LogActivityController::class, 'synchronized_data'])->name('transaction.synchronized-data');
    Route::resource('transaction', TransactionController::class)->only(['index', 'store', 'show']);
    
    Route::resource('users', UserController::class)->only(['index', 'store', 'destroy']);
    Route::post('user/change-role/{user}', [UserController::class, 'changeRole'])->name('user.change-role');
    Route::post('user/change-password/{user}', [UserController::class, 'changePassword'])->name('user.change-password');
    
    Route::get('report-tickets', [ReportController::class, 'reportTickets'])->name('report.tickets');
    Route::post('report-tickets/export', [ReportController::class, 'exportTickets'])->name('report.export.tickets');
    Route::get('report-store', [ReportController::class, 'reportStore'])->name('report.store');
    Route::post('report-store/export', [ReportController::class, 'exportStore'])->name('report.export.store');

    Route::resource('log-activities', LogActivityController::class)->only(['index', 'destroy']);
});

Route::get('customer-display/{type}', [Controller::class, 'customer_display'])->name('customer.display');
Route::get('product-display/{name}/{price}', [ProductController::class, 'display_product'])->name('product.display');

app/Models/Product.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model {

    use HasFactory;

    const IMAGE_PATH = 'product/';

    const ID = 'id';
    const NAME = 'name';
    const CODE = 'code';
    const INVENTORY = 'inventory';
    const PRICE = 'price';
    const CAPITAL_PRICE = 'capital_price';
    const IMAGE = 'image';
    const DESC = 'desc';

    protected $guarded = [];
    protected $primaryKey = Self::ID;
    public $incrementing = false;
    protected $keyType = 'string';

    protected function serializeDate(DateTimeInterface $date) {
        return $date->format('Y-m-d H:i:s');
    }

    function saleItems() {
        return $this->hasMany(ProductSale::class);
    }

    function scopeGenerateProductId() {
        $characters = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $id = 'PRODUCT-';

        for ($i = 0; $i < 16; $i++) 
            $id .= $characters[random_int(0, strlen($characters) - 1)];

        if ($this->productIdExists($id)) return $this->scopeGenerateProductId();

        return $id;
    }

    function productIdExists($id) {
        return $this->where(Self::ID, $id)->exists();
    }

    function getImageAttribute($value) {
        if ($value == null) return asset('assets/img/not_found.png');
        else return asset('storage/'.Self::IMAGE_PATH.$value);
    }

    function decrementStok($qty = 1) {
        $inventory = $this->attributes[Self::INVENTORY] - $qty;
        $this->update([Self::INVENTORY => $inventory]);
        return;
    }

    function incrementStok($qty = 1) {
        $inventory = $this->attributes[Self::INVENTORY] + $qty;
        $this->update([Self::INVENTORY => $inventory]);
        return;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Exports\ProductExport;
use App\Models\Product;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Excel;

class ProductController extends Controller {
    
    function __construct() {
        $this->middleware('permission:view-products')->only('index');
        $this->middleware('permission:create-products')->only('create','store');
        $this->middleware('permission:edit-products')->only('show','update');
        $this->middleware('permission:delete-products')->only('destroy');
    }

    public function index() {
        if (request()->ajax()) {
            $products = Product::get();
            return response(['status' => true, 'data' => $products]);
        }

        return view('product.index');
    }

    public function create() {
        return view('product.create');
    }

    public function store(Request $request) {
        $request->validate([
            Product::NAME => 'required|string',
            Product::CODE => 'required|min:6|unique:products,code',
            Product::INVENTORY => 'required|numeric',
            Product::CAPITAL_PRICE => 'numeric',
            Product::PRICE => 'required|numeric|min:1',
            Product::IMAGE => 'image|mimes:jpg,jpeg,png|max:2048',
            Product::DESC => 'nullable',
        ]);
        
        DB::beginTransaction();
        
        try {
            $product_id = Product::generateProductId();
            $payload = $request->except(Product::IMAGE);
            $payload[Product::ID] = $product_id;
            $capital_price = $request->input(Product::CAPITAL_PRICE) != '' ? $request->input(Product::CAPITAL_PRICE) : 0;
            $payload[Product::CAPITAL_PRICE] = $capital_price != 0 ? $capital_price : $request->input(Product::PRICE) - 1000;
            
            if ($request->has(Product::IMAGE)) {
                $image = Storage::disk('public')->put(Product::IMAGE_PATH, $request->file(Product::IMAGE));
                $payload[Product::IMAGE] = basename($image);
            }
    
            Product::create($payload);
    
            DB::commit();
            return redirect()->route('products.index')->with(['status' => 'Produk', 'message' => 'baru berhasil tersimpan.']);
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->back()->with(['status' => 'error', 'message' => 'Produk gagal tersimpan.']);
        }
    }

    public function show(Product $product) {
        // return response($product);
        return view('product.show', compact('product'));
    }

    public function update(Request $request, Product $product) {
        $request->validate([
            Product::NAME => 'required|string',
            Product::CODE => 'required|min:6|unique:products,code,'.$product->id,
            Product::INVENTORY => 'required|numeric',
            Product::CAPITAL_PRICE => 'numeric',
            Product::PRICE => 'required|numeric|min:1',
            Product::IMAGE => 'image|mimes:jpg,jpeg,png|max:2048',
            Product::DESC => 'nullable',
        ]);

        if (auth()->user()->hasRole('owner'))
            $payload = $request->except(Product::IMAGE);
        else
            $payload = $request->except(Product::IMAGE, Product::INVENTORY);
        
        $capital_price = $request->input(Product::CAPITAL_PRICE) != '' ? $request->input(Product::CAPITAL_PRICE) : 0;
        $payload[Product::CAPITAL_PRICE] = $capital_price != 0 ? $capital_price : $request->input(Product::PRICE) - 1000;

        if ($request->has(Product::IMAGE)) {
            $arr_image = explode('/',$product->image);
            if (end($arr_image) != 'not_found.png') {
                Storage::disk('public')->delete(Product::IMAGE_PATH.end($arr_image));
            }
            $image = Storage::disk('public')->put(Product::IMAGE_PATH, $request->file(Product::IMAGE));
            $payload[Product::IMAGE] = basename($image);
        }

        $product->update($payload);

        return redirect()->route('products.index')->with(['status' => 'Produk', 'message' => 'berhasil diperbarui.']);
    }

    public function destroy(Product $product) {
        $arr_image = explode('/',$product->image);
        if (end($arr_image) != 'not_found.png') {
            Storage::disk('public')->delete(Product::IMAGE_PATH.end($arr_image));
        }
        $product->delete();

        return response(['status' => true, 'message' => 'Produk Berhasil Terhapus.']);
    }

    function print_barcode($code) {
        $product = Product::where(Product::CODE, $code)->firstOrFail();

        return view('product.barcode', compact('product'));
    }

    function display_product($name, $price) {
        try {
            $this->customer_display('product', $name, (int) $price);

            return response(['status' => true, 'message' => 'Display changed.']);
        } catch (\Throwable $th) {
            return response(['status' => false, 'message' => $th->getMessage()]);
        }
    }

    function export() {
        return Excel::download(new ProductExport(), 'Katalog Produk MUSEUM GALERI SBYANI - '.Carbon::now()->format('d-m-Y').'.xlsx');
    }
}

resources/views/product/barcode.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cetak Barcode</title>
    <link href='{{ asset('assets/css/font-family-inter.css') }}' rel='stylesheet'>
    <style>
        body {
            font-family: 'Inter';
            text-align:center;
            margin-top: 6px;
            margin-bottom: 0px;
        }
        #price {
            margin-top: 0px;
            margin-bottom: 5px;
            font-size:12px;
            font-weight: bold;
        }
        #code {
            margin-top: -5px;
            font-size:8px;
            letter-spacing: 5px;
        }
    </style>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            window.print();
            setTimeout(() => {
                window.close()
            }, 500);

        });
    </script>
</head>
<body>
    <p id="price"> Rp. {{ number_format($product->price,0,'','.') }} </p>

    @php
        $generatorPNG = new Picqer\Barcode\BarcodeGeneratorPNG();
    @endphp

    <img src="data:image/png;base64,{{ base64_encode($generatorPNG->getBarcode($product->code, $generatorPNG::TYPE_CODE_128, 1,20)) }}">

    <p id="code" >{{ $product->code }}</p>
</body>
</html>

resources/views/product/create.blade.php
@extends('layout.main')

@section('title', 'Tambah Produk Baru')

@section('content')
<section class="section">
    <div class="row">
        <div class="col-12 col-lg-10">
            <div class="card">
                <form action="{{ route('products.store') }}" method="POST" id="form-product" enctype="multipart/form-data">
                    <div class="card-body pb-1">
                        @csrf
                        <div class="row">
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <label>Nama Produk</label>
                                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder=". . . ." >
                                    @error('name') <div class="invalid-feedback">{{ $message }}</div> @enderror
                                </div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <label>Kode Produk</label>
                                    <input type="text" name="code" class="form-control @error('code') is-invalid @enderror" placeholder=". . . .">
                                    @error('code') <div class="invalid-feedback">{{ $message }}</div> @enderror
                                </div> 
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Deskripsi</label>
                            <textarea name="desc" rows="4" style="height: auto !important" class="form-control"></textarea>
                        </div>
                        <div class="row">
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <label>Harga</label>
                                    <input type="number" name="price" class="form-control @error('price') is-invalid @enderror" required value="0" min="0">
                                    @error('price') <div class="invalid-feedback">{{ $message }}</div> @enderror
                                </div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <label>Inventory</label>
                                    <input type="number" name="inventory" class="form-control @error('inventory') is-invalid @enderror" required value="0" min="0">
                                    @error('inventory') <div class="invalid-feedback">{{ $message }}</div> @enderror
                                </div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <label>Gambar</label>
                                    <img class="d-block mx-2 mb-2 mt-0 file-image" src="{{ asset('assets/img/not_found.png') }}" alt="" style="height: 140px;">
                                    <input type="file" name="image" class="form-control pt-2 @error('image') is-invalid @enderror" accept="image/*">
                                    @error('image') <div class="invalid-feedback">{{ $message }}</div> @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer pt-0">
                        <button class="btn btn-warning" type="submit"><i class="fas fa-plus mr-2"></i> Tambahkan Produk Baru</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection

@push('addons-style')
<style>
    input[type="file"]:hover {
        cursor: pointer;
    }
    .file-image{
        max-width:100%;
        filter: drop-shadow(0px 2px 6px #636262);
    }
    .file-image:hover{
        cursor: pointer;
        filter: drop-shadow(0px 2px 6px #333333);
    }
</style>
@endpush

@push('addons-script')
<script>
    let image = "{{ asset('assets/img/not_found.png') }}";
    $(document).ready(function () {
        $('.file-image').click(function (e) { 
            e.preventDefault();
            $('input[name="image"]').click();
        });
    });

    $('input[name="image"]').on("change", function() {
        if ($(this).val() == '') {
            $('.file-image').attr("src",image);
        } else {
            let reader = new FileReader();
            reader.onload = (e) => { 
                $('.file-image').attr("src",e.target.result);
            }
            reader.readAsDataURL(this.files[0]); 
        }
    });
</script>
@endpush

resources/views/product/index.blade.php
@extends('layout.main')
@section('title','Daftar Produk')

@section('content')
<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card card-warning">
                {{-- <div class="card-header">
                    <h4>Basic DataTables</h4>
                </div> --}}
                <form action="{{ route('export.products') }}" method="POST" id="form-export-product" style="display: none">
                    @csrf
                </form>
                <div class="card-body">
                    <div class="table-responsive" >
                        <table class="table table-striped" id="table-products" style="width: 100%">
                            <thead>
                                <tr>
                                    <th class="text-center">No.</th>
                                    <th></th>
                                    <th>Nama</th>
                                    <th>Kode</th>
                                    <th>Inventory</th>
                                    <th>Harga @</th>
                                    <th class="text-center">Created At</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal Print -->
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-info" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Konfirmasi Hapus</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                Apakah anda yakin ingin menghapus Tiket ini ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger" id="btn-delete-products">Hapus</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal Delete -->
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Konfirmasi Hapus</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                Apakah anda yakin ingin menghapus Produk ini ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger" id="btn-delete-products">Hapus</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('addons-style')
<link rel="stylesheet" href="assets/bundles/datatables/datatables.min.css">
<link rel="stylesheet" href="assets/bundles/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css">
<style>
    table.dataTable img {
        -webkit-box-shadow: 0 5px 15px 0 rgba(105,103,103,0.5);
        box-shadow: 0 5px 15px 0 rgba(105,103,103,0.5);
        border: 0px solid #ffffff;
        border-radius: 2px;
    }
    .btn-purple {
        box-shadow: 0 2px 6px #7a35f8;
        background-color: #6d31dd;
        border-color: #6d31dd;
        color: white;
    }
    .btn-purple:hover,.btn-purple:active,.btn-purple:focus {
        background-color: #7a35f8 !important;
        color: white;
    }
</style>
@endpush

@push('addons-script')
<!-- JS Libraies -->
<script src="assets/bundles/datatables/datatables.min.js"></script>
<script src="assets/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script src="assets/bundles/jquery-ui/jquery-ui.min.js"></script>
<script src="https://cdn.datatables.net/plug-ins/1.13.5/sorting/natural.js"></script>
<!-- Page Specific JS File -->
<script src="assets/js/page/datatables.js"></script>

<script>
    var product_id = 1;

    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': "{{ csrf_token() }}"
            }
        })
        let dt_products = $('#table-products').DataTable( {
            processing: true,
            ajax: "{!! url()->current() !!}",
            order: [[6, 'desc']],
            columns: [
                { data: null, width: "10px", sClass: "text-center", bSortable: false },
                { data: "null", sClass: "text-center", render: function ( data, type, row ) {
                        return `<img alt="image" src="`+row.image+`" height="45px">`;
                    },bSortable: false
                },
                { data: "name" },
                { data: "code" },
                { data: "inventory", sClass: "text-right" },
                { data: "null", type: 'natural', sClass: "text-right", render: function ( data, type, row ) {
                        return formatRupiah(row.price);
                    }
                },
                { data: "created_at", sClass: "text-center" },
                { data: "null", sClass: "text-center", render: function ( data, type, row ) {
                        let url_detail = "{{ route('products.show', ':id') }}";
                        return `
                            <a href="`+url_detail.replace(':id', row.id)+`" class="btn btn-sm btn-success" title="update" style="color:white"><i class="fas fa-pencil-alt mr-1"></i> Update</a>
                            <button class="btn btn-sm btn-info" onclick="printBarcode('`+row.code+`')"><i class="fas fa-barcode mr-1"></i> Cetak</button>
                            <button class="btn btn-sm btn-danger" onclick="deleteProduct('`+row.id+`')"><i class="fa fa-trash mr-1"></i> Hapus</button>
                        `;
                    },bSortable: false
                }
            ],
            initComplete: function(){
                $("#table-products_filter").parent().after(`
                    <div class="col-12 col-md-4 text-center text-md-right">
                        <button class="btn btn-rounded btn-purple mb-2" id="btn-export"><i class="fa fa-print mr-2"></i> Export Data</button>
                        <a href="{{ route('products.create') }}" class="btn btn-rounded btn-warning mb-2" style="color:white"><i class="fa fa-plus mr-2"></i> Tambahkan Produk Baru</a>
                    </div>
                `);
                $("#table-products_length").parent().addClass('col-12 col-sm-6 col-md-4').removeClass('col-sm-12 col-md-6')
                $("#table-products_filter").css('text-align', 'center');
                $("#table-products_filter").parent().addClass('col-12 col-sm-6 col-md-4').removeClass('col-sm-12 col-md-6')
            }   
        });
        dt_products.on( 'order.dt search.dt', function () {
            dt_products.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                cell.innerHTML = i+1;
            } );
        } ).draw();

        $('#btn-delete-products').click(function (e) { 
            e.preventDefault();
            let url_delete = "{{ route('products.destroy', ':id') }}";

            $.ajax({
                type: "DELETE",
                url: url_delete.replace(':id', product_id),
                success: function (response) {
                    if (response.status) {
                        dt_products.ajax.reload(function () {
                            $('#modal-delete').modal('hide');
                            showAlert('success',response.message,'Berhasil')
                        }, false);
                    }
                },
            });
        });

        $('#table-products_wrapper').on('click', 'button#btn-export', function () {
            $('#form-export-product').submit();
        });
    });

    function deleteProduct(id) {
        product_id = id;
        $('#modal-delete').modal('show');
    }

    function printBarcode(code) {
        let url_print = "{{ route('product.print-barcode', ':id') }}";

        popupCenter({url: url_print.replace(':id', code), title: 'xtf', w: 700, h: 440}); 
    }
</script>
@endpush

resources/views/product/show.blade.php
@extends('layout.main')

@section('title', 'Data Lengkap Produk')

@section('content')
<section class="section">
    <div class="row">
        <div class="col-10">
            <div class="card">
                <form action="{{ route('products.update', $product->id) }}" method="POST" id="form-product" enctype="multipart/form-data">
                    <div class="card-body pb-1">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <label>Nama Produk</label>
                                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder=". . . ." value="{{ $product->name }}">
                                    @error('name') <div class="invalid-feedback">{{ $message }}</div> @enderror
                                </div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <label>Kode Produk</label>
                                    <input type="text" name="code" class="form-control @error('code') is-invalid @enderror" placeholder=". . . ." value="{{ $product->code }}">
                                    @error('code') <div class="invalid-feedback">{{ $message }}</div> @enderror
                                </div> 
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Deskripsi</label>
                            <textarea name="desc" rows="4" style="height: auto !important" class="form-control">{{ $product->desc }}</textarea>
                        </div>
                        <div class="row">
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <label>Harga Jual</label>
                                    <input type="number" name="price" class="form-control @error('price') is-invalid @enderror" required value="{{ $product->price }}">
                                    @error('price') <div class="invalid-feedback">{{ $message }}</div> @enderror
                                </div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <label>Inventory</label>
                                    <input type="number" name="inventory" class="form-control @error('inventory') is-invalid @enderror" required value="{{ $product->inventory }}" @hasanyrole('pos|ticket') disabled @endhasanyrole>
                                    @error('inventory') <div class="invalid-feedback">{{ $message }}</div> @enderror
                                </div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <label>Gambar</label>
                                    <img class="d-block mx-2 mb-2 mt-0 file-image" src="{{ $product->image }}" alt="" style="height: 140px;">
                                    <input type="file" name="image" class="form-control pt-2 @error('image') is-invalid @enderror" accept="image/*">
                                    @error('image') <div class="invalid-feedback">{{ $message }}</div> @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer pt-0">
                        <button class="btn btn-warning" type="submit"><i class="fas fa-edit mr-2"></i> Update Data Produk</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection

@push('addons-style')
<style>
    input[type="file"]:hover {
        cursor: pointer;
    }
    .file-image{
        max-width:100%;
        filter: drop-shadow(0px 2px 6px #636262);
    }
    .file-image:hover{
        cursor: pointer;
        filter: drop-shadow(0px 2px 6px #333333);
    }
</style>
@endpush

@push('addons-script')
<script>
    let image = "{{ $product->image }}";
    $(document).ready(function () {
        $('.file-image').click(function (e) { 
            e.preventDefault();
            $('input[name="image"]').click();
        });
    });

    $('input[name="image"]').on("change", function() {
        if ($(this).val() == '') {
            $('.file-image').attr("src",image);
        } else {
            let reader = new FileReader();
            reader.onload = (e) => { 
                $('.file-image').attr("src",e.target.result);
            }
            reader.readAsDataURL(this.files[0]); 
        }
    });
</script>
@endpush