routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LogActivityController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductSaleController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\TicketSaleController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::group(['namespace' => 'Auth'], function() {
    Route::get('login', [LoginController::class,'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class,'login'])->name('login.store');
    Route::post('logout', [LoginController::class,'logout'])->name('logout')->middleware('auth');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function() { return redirect()->route('dashboard'); });
    Route::get('dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
    Route::get('dashboard-ticket', [DashboardController::class, 'ticket'])->name('dashboard.ticket');
    Route::get('dashboard-store', [DashboardController::class, 'store'])->name('dashboard.store');
    
    Route::resource('tickets', TicketController::class)->only(['destroy']);
    Route::get('tickets-valid', [TicketController::class, 'valid'])->name('ticket.valid');
    Route::get('tickets-invalid', [TicketController::class, 'invalid'])->name('ticket.invalid');
    Route::post('ticket-import', [TicketController::class, 'import'])->name('ticket.import');

    Route::resource('ticket-sales', TicketSaleController::class)->only(['index','destroy']);

    Route::resource('products', ProductController::class)->except(['edit']);
    Route::get('product-barcode/{code}', [ProductController::class, 'print_barcode'])->name('product.print-barcode');
    Route::post('export/products', [ProductController::class, 'export'])->name('export.products');

    Route::resource('product-sales', ProductSaleController::class)->only(['index', 'show', 'destroy']);

    Route::get('transaction/synchronized-data', [LogActivityController::class, 'synchronized_data'])->name('transaction.synchronized-data');
    Route::resource('transaction', TransactionController::class)->only(['index', 'store', 'show']);
    
    Route::resource('users', UserController::class)->only(['index', 'store', 'destroy']);
    Route::post('user/change-role/{user}', [UserController::class, 'changeRole'])->name('user.change-role');
    Route::post('user/change-password/{user}', [UserController::class, 'changePassword'])->name('user.change-password');
    
    Route::get('report-tickets', [ReportController::class, 'reportTickets'])->name('report.tickets');
    Route::post('report-tickets/export', [ReportController::class, 'exportTickets'])->name('report.export.tickets');
    Route::get('report-store', [ReportController::class, 'reportStore'])->name('report.store');
    Route::post('report-store/export', [ReportController::class, 'exportStore'])->name('report.export.store');

    Route::resource('log-activities', LogActivityController::class)->only(['index', 'destroy']);
});

Route::get('customer-display/{type}', [Controller::class, 'customer_display'])->name('customer.display');
Route::get('product-display/{name}/{price}', [ProductController::class, 'display_product'])->name('product.display');

app/Models/TicketSale.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TicketSale extends Model {

    use HasFactory;

    const ID = 'id';
    const USER_ID = 'user_id';
    const PAYMENT_ID = 'type_payment_id';
    const CUST_NAME = 'cust_name';
    const TOTAL_PRICE = 'total_price';
    const DISCOUNT = 'discount';
    const FINAL_AMOUNT = 'final_amount';
    const PAID_AMOUNT = 'paid_amount';
    const CHANGE = 'change';
    const NOTE = 'note';
    const IS_COMPLETED = 'is_completed';

    protected $guarded = [];
    protected $primaryKey = Self::ID;
    public $incrementing = false;
    protected $keyType = 'string';

    protected function serializeDate(DateTimeInterface $date) {
        return $date->format('Y-m-d H:i:s');
    }

    function user() {
        return $this->belongsTo(User::class)->withTrashed();
    }

    function items() {
        return $this->hasMany(TicketSaleItem::class, TicketSaleItem::SALE_ID);
    }

    function payment() {
        return $this->belongsTo(TypePayment::class, Self::PAYMENT_ID);
    }

    function scopeGenerateTicketId() {
        $characters = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $id = 'SBY*ANI-';

        for ($i = 0; $i < 12; $i++) 
            $id .= $characters[random_int(0, strlen($characters) - 1)];

        if ($this->ticketIdExists($id)) return $this->scopeGenerateTicketId();

        return $id;
    }

    function ticketIdExists($id) {
        return $this->where(Self::ID, $id)->exists();
    }
}

app/Http/Controllers/TicketSaleController.php
<?php

namespace App\Http\Controllers;

use App\Models\TicketSale;
use App\Models\TicketSaleItem;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use DataTables;

class TicketSaleController extends Controller {

    function __construct() {
        $this->middleware('permission:view-sale-tickets')->only('index');
    }

    public function index() {
        if (request()->ajax()) {
            // $sales = TicketSale::with('user','payment','items')->withSum('items', TicketSaleItem::QTY)->latest()->get();
            // return response(['status' => true, 'data' => $sales]);

            $sales = TicketSale::with('user','payment','items')->withSum('items', TicketSaleItem::QTY);
            return Datatables::eloquent($sales)
                ->addIndexColumn()
                ->addColumn('name', function (TicketSale $sale) {
                    return '<p class="mb-0">'.$sale->cust_name.'</p><small>'.$sale->user->name.'</small>';
                })
                ->addColumn('total', function(TicketSale $sale) {
                    return '<p class="mb-1">Rp. '.number_format($sale->total_price, 0, '', '.').'</p><small>- Rp. '.number_format($sale->discount, 0, '', '.').'</small>';
                })
                ->addColumn('final', function(TicketSale $sale) {
                    return '<h6 class="mb-0"><b>Rp. '.number_format($sale->final_amount, 0, '', '.').'</b></h6><small>'.$sale->id.'</small>';
                })
                ->addColumn('paid', function(TicketSale $sale) {
                    return '<p class="mb-0">Rp. '.number_format($sale->paid_amount, 0, '', '.').'</p><small> Rp. '.number_format($sale->change, 0, '', '.').'</small>';
                })
                ->addColumn('sum_qty', function($row) {
                    return $row->items_sum_qty.' Tiket';
                })
                ->addColumn('tickets', function($row){
                    $html = '<small>';
                    foreach ($row->items as $key => $value) {
                        $html .= $value->qty.' x '.$value->name.'<br>';
                    };
                    return $html .= '</small>';
                })
                ->addColumn('status', function(TicketSale $sale) {
                    if ($sale->is_completed)
                        return '<span class="badge badge-sm badge-success"> Selesai </span>';
                    else 
                        return '<span class="badge badge-sm badge-secondary"> Pending </span>';
                })
                ->rawColumns(["name", 'total', 'final', 'paid','tickets', 'status'])
                ->blacklist(['DT_RowIndex','status'])
                ->toJson();
        }

        return view('ticket-sale.index');
    }
}

resources/views/ticket-sale/index.blade.php
@extends('layout.main')
@section('title','Riwayat Penjualan Tiket')

@section('content')
<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card card-warning">
                {{-- <div class="card-header">
                    <h4>Basic DataTables</h4>
                </div> --}}
                <div class="card-body">
                    <div class="table-responsive" >
                        <table class="table table-striped" id="table-sales" style="width: 100%">
                            <thead>
                                <tr>
                                    <th class="text-center">No.</th>
                                    <th>Pengunjung</th>
                                    <th>Jumlah Harga</th>
                                    <th style="font-weight: 900"> Total Harga & ID</th>
                                    <th>Pembayaran</th>
                                    <th>Metode</th>
                                    <th>Jumlah</th>
                                    <th>Jenis Ticket</th>
                                    <th>Status</th>
                                    <th>Catatan</th>
                                    <th class="text-center">Tanggal</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal -->
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Konfirmasi Hapus</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                Apakah anda yakin ingin menghapus Riwayat ini ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger" id="btn-delete-sale">Hapus</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('addons-style')
<link rel="stylesheet" href="{{ ('assets/bundles/datatables/datatables.min.css') }}">
<link rel="stylesheet" href="{{ ('assets/bundles/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css') }}">
@endpush

@push('addons-script')
<!-- JS Libraies -->
<script src="{{ ('assets/bundles/datatables/datatables.min.js') }}"></script>
<script src="{{ ('assets/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ ('assets/bundles/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Page Specific JS File -->
<script src="{{ ('assets/js/page/datatables.js') }}"></script>

<script>
    var sale_id = 1;

    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': "{{ csrf_token() }}"
            }
        })
        let dt_tickets = $('#table-sales').DataTable({
            processing: true,
            serverSide: true,
            paging:true,
            ajax: "{!! url()->current() !!}",
            pageLength: 50,
            order: [[10, 'desc']],
            scrollY: 600,
            scrollCollapse: true,
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex', sClass: "text-center", orderable: false, searchable: false, bSortable: false},
                {data: 'name', name: 'cust_name'},
                {data: 'total', name: 'total_price', type: 'natural'},
                {data: 'final', name: 'final_amount', type: 'natural'},
                {data: 'paid', name: 'paid_amount', type: 'natural'},
                {data: 'payment.name', name: 'payment.name'},
                {data: 'sum_qty', name: 'items.qty'},
                {data: 'tickets', name: 'items.name'},
                {data: 'status', name: 'is_completed', sClass: "text-center"},
                {data: 'note', name: 'note'},
                {data: 'created_at', name: 'created_at', sClass: "text-center"},
                {data: 'id', name: 'id', visible:false},
                {data: 'user.name', name: 'user.name', visible:false}
            ],
            'initComplete': function(){
                $("#table-sales_filter").parent().after(`
                    <div class="col-12 col-md-4 text-center text-md-right">
                        
                    </div>
                `);
                $("#table-sales_length").parent().addClass('col-12 col-sm-6 col-md-4').removeClass('col-sm-12 col-md-6')
                $("#table-sales_filter").css('text-align', 'center');
                $("#table-sales_filter").parent().addClass('col-12 col-sm-6 col-md-4').removeClass('col-sm-12 col-md-6')
            }
        });
        dt_tickets.on( 'order.dt search.dt', function () {
            dt_tickets.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                cell.innerHTML = i+1;
            } );
        } ).draw();

        $('#btn-delete-sale').click(function (e) { 
            e.preventDefault();
            let url_delete = "{{ route('ticket-sales.destroy', ':id') }}";

            $.ajax({
                type: "DELETE",
                url: url_delete.replace(':id', sale_id),
                success: function (response) {
                    if (response.status) {
                        dt_tickets.ajax.reload(function () {
                            $('#modal-delete').modal('hide');
                            showAlert('success',response.message,'Berhasil')
                        }, false);
                    }
                },
            });
        });
    });

    function importTickets() {
        $('#input-file-import').click();
    }

    $('#input-file-import').on('change', function(){ 
        if ($(this).get(0).files.length != 0) {
            $( "#form-import" ).submit();
        }
    });

    function deleteSale(id) {
        sale_id = id;
        $('#modal-delete').modal('show');
    }
</script>
@endpush

resources/views/ticket-sale/index_0.blade.php
@extends('layout.main')
@section('title','Riwayat Penjualan Tiket')

@section('content')
<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card card-warning">
                {{-- <div class="card-header">
                    <h4>Basic DataTables</h4>
                </div> --}}
                <div class="card-body">
                    <div class="table-responsive" >
                        <table class="table table-striped" id="table-sales" style="width: 100%">
                            <thead>
                                <tr>
                                    <th class="text-center">No.</th>
                                    <th>Pengunjung</th>
                                    <th>Jumlah Harga</th>
                                    <th style="font-weight: 900"> Total Harga & ID</th>
                                    <th>Pembayaran</th>
                                    <th>Metode</th>
                                    <th>Jumlah</th>
                                    <th>Jenis Ticket</th>
                                    <th>Status</th>
                                    <th>Catatan</th>
                                    <th class="text-center">Tanggal</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal -->
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Konfirmasi Hapus</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                Apakah anda yakin ingin menghapus Riwayat ini ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger" id="btn-delete-sale">Hapus</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('addons-style')
<link rel="stylesheet" href="assets/bundles/datatables/datatables.min.css">
<link rel="stylesheet" href="assets/bundles/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css">
@endpush

@push('addons-script')
<!-- JS Libraies -->
<script src="assets/bundles/datatables/datatables.min.js"></script>
<script src="assets/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script src="assets/bundles/jquery-ui/jquery-ui.min.js"></script>
<!-- Page Specific JS File -->
<script src="assets/js/page/datatables.js"></script>

<script>
    var sale_id = 1;

    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': "{{ csrf_token() }}"
            }
        })
        let dt_tickets = $('#table-sales').DataTable( {
            "processing": true,
            "ajax": "{!! url()->current() !!}",
            "columns": [
                {
                    "data": null,
                    "width": "10px",
                    "sClass": "text-center",
                    "bSortable": false
                },
                { "data": "null", render: function ( data, type, row ) {
                        return '<p class="mb-0">'+row.cust_name+'</p><small>'+row.user.name+'</small>'
                    }
                },
                { "data": "null", "sClass": "text-right", render: function ( data, type, row ) {
                        return '<p class="mb-1">'+formatRupiah(row.total_price)+'</p><small>- '+formatRupiah(row.discount)+'</small>';
                    }
                },
                { "data": "null", "sClass": "text-right", render: function ( data, type, row ) {
                        return '<h6 class="mb-0"><b>'+formatRupiah((row.final_amount))+'</b></h6><small>'+row.id+'</small>';
                    }
                },
                { "data": "null", "sClass": "text-right", render: function ( data, type, row ) {
                        return '<p class="mb-0">'+formatRupiah(row.paid_amount)+'</p><small> '+formatRupiah(row.change)+'</small>';
                    }
                },
                { "data": "payment.name"},
                { "data": "null", "sClass": "text-right", render: function ( data, type, row ) {
                        return row.items_sum_qty+' Tiket';
                    }
                },
                { "data": "null", "sClass": "text-right", render: function ( data, type, row ) {
                        let html = '<small>';
                        $.each(row.items, function (index, value) { 
                            html += value.qty+' x '+value.name+'<br>'
                        });
                        return html += '</small>';
                    }
                },
                { "data": "null", "sClass": "text-center", render: function ( data, type, row ) {
                        return row.is_completed ? '<span class="badge badge-sm badge-success"> Selesai </span>' : '<span class="badge badge-sm badge-secondary"> Pending </span>';
                    }
                },
                { "data": "note"},
                { "data": "created_at", "sClass": "text-center" },
            ],
            'initComplete': function(){
                $("#table-sales_filter").parent().after(`
                    <div class="col-12 col-md-4 text-center text-md-right">
                        
                    </div>
                `);
                $("#table-sales_length").parent().addClass('col-12 col-sm-6 col-md-4').removeClass('col-sm-12 col-md-6')
                $("#table-sales_filter").css('text-align', 'center');
                $("#table-sales_filter").parent().addClass('col-12 col-sm-6 col-md-4').removeClass('col-sm-12 col-md-6')
            }  
        });
        dt_tickets.on( 'order.dt search.dt', function () {
            dt_tickets.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                cell.innerHTML = i+1;
            } );
        } ).draw();

        $('#btn-delete-sale').click(function (e) { 
            e.preventDefault();
            let url_delete = "{{ route('ticket-sales.destroy', ':id') }}";

            $.ajax({
                type: "DELETE",
                url: url_delete.replace(':id', sale_id),
                success: function (response) {
                    if (response.status) {
                        dt_tickets.ajax.reload(function () {
                            $('#modal-delete').modal('hide');
                            showAlert('success',response.message,'Berhasil')
                        }, false);
                    }
                },
            });
        });
    });

    function importTickets() {
        $('#input-file-import').click();
    }

    $('#input-file-import').on('change', function(){ 
        if ($(this).get(0).files.length != 0) {
            $( "#form-import" ).submit();
        }
    });

    function deleteSale(id) {
        sale_id = id;
        $('#modal-delete').modal('show');
    }
</script>
@endpush

resources/views/ticket-sale/show.blade.php
@extends('layout.main')
@section('title', 'Informasi Detail Penjualan Tiket')

@section('content')
<div class="row">
    <div class="col-12 col-lg-5">
        <div class="card">
            <div class="card-header">
                <h4>Informasi Penjualan</h4>
            </div>
            <div class="card-body" style="height: 700px;">
                <table class="table w-100">
                    <tbody>
                        <tr>
                            <td>ID Transaksi</td>
                            <td>:</td>
                            <td>{{ $sale->id }}</td>
                        </tr>
                        <tr>
                            <td>Nama Pengunjung</td>
                            <td>:</td>
                            <td>{{ $sale->cust_name }}</td>
                        </tr>
                        <tr>
                            <td>Jenis Pembayaran</td>
                            <td>:</td>
                            <td>{{ $sale->payment->name }}</td>
                        </tr>
                        <tr>
                            <td>Petugas Loket</td>
                            <td>:</td>
                            <td>{{ $sale->user->name }}</td>
                        </tr>
                        <tr>
                            <td>Jumlah Tiket</td>
                            <td>:</td>
                            <td>{{ $sale->items_count }}</td>
                        </tr>
                        <tr>
                            <td>Total Harga</td>
                            <td>:</td>
                            <td>Rp. {{ $sale->total_price }}</td>
                        </tr>
                        <tr>
                            <td>Status</td>
                            <td>:</td>
                            <td>
                                @if ($sale->is_completed)
                                    <span class="badge badge-sm badge-success">Selesai</span>
                                @else
                                    <span class="badge badge-sm badge-warning">Pending</span>
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <td>Catatan</td>
                            <td>:</td>
                            <td>{{ $sale->note }}</td>
                        </tr>
                        <tr>
                            <td>Tanggal</td>
                            <td>:</td>
                            <td>{{ $sale->created_at }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-12 col-lg-7">
        <div class="card">
            <div class="card-header">
                <h4>Informasi Tiket.</h4>
            </div>
            <div class="card-body" style="height: 700px;overflow-y: scroll;">
                @foreach ($sale->items as $item)
                    <div class="row py-2">
                        <div class="col-12 col-lg-6" style="white-space: nowrap;">
                            <span class="mr-3"><b>{{ $loop->iteration }}</b></span>
                            @if (str_contains($item->type, ' Domestik'))
                                <img src="{{ asset('assets/img/ticket/tiket_domestik.jpg') }}" alt="" srcset="" style="width:90%;max-width:360px">
                            @elseif (str_contains($item->type, ' Nasional'))
                                <img src="{{ asset('assets/img/ticket/tiket_nasional.jpg') }}" alt="" srcset="" style="width:90%;max-width:360px">
                            @else 
                                <img src="{{ asset('assets/img/ticket/tiket_internasional.jpg') }}" alt="" srcset="" style="width:90%;max-width:360px">
                            @endif
                        </div>
                        <div class="col-12 col-lg-6 pl-lg-0 pt-3 pt-lg-4 text-center text-lg-left">
                            <h6>{{ $item->type }}</h6>
                            <p class="my-0" style="color: #6c757d"><b>Kode : {{ $item->ticket->barcode }}</b></p>
                            <p class="my-0" style="color: #6c757d"><b>Harga : {{ $item->price }}</b></p>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
</div>
@endsection