routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LogActivityController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductSaleController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\TicketSaleController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::group(['namespace' => 'Auth'], function() {
    Route::get('login', [LoginController::class,'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class,'login'])->name('login.store');
    Route::post('logout', [LoginController::class,'logout'])->name('logout')->middleware('auth');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function() { return redirect()->route('dashboard'); });
    Route::get('dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
    Route::get('dashboard-ticket', [DashboardController::class, 'ticket'])->name('dashboard.ticket');
    Route::get('dashboard-store', [DashboardController::class, 'store'])->name('dashboard.store');
    
    Route::resource('tickets', TicketController::class)->only(['destroy']);
    Route::get('tickets-valid', [TicketController::class, 'valid'])->name('ticket.valid');
    Route::get('tickets-invalid', [TicketController::class, 'invalid'])->name('ticket.invalid');
    Route::post('ticket-import', [TicketController::class, 'import'])->name('ticket.import');

    Route::resource('ticket-sales', TicketSaleController::class)->only(['index','destroy']);

    Route::resource('products', ProductController::class)->except(['edit']);
    Route::get('product-barcode/{code}', [ProductController::class, 'print_barcode'])->name('product.print-barcode');
    Route::post('export/products', [ProductController::class, 'export'])->name('export.products');

    Route::resource('product-sales', ProductSaleController::class)->only(['index', 'show', 'destroy']);

    Route::get('transaction/synchronized-data', [LogActivityController::class, 'synchronized_data'])->name('transaction.synchronized-data');
    Route::resource('transaction', TransactionController::class)->only(['index', 'store', 'show']);
    
    Route::resource('users', UserController::class)->only(['index', 'store', 'destroy']);
    Route::post('user/change-role/{user}', [UserController::class, 'changeRole'])->name('user.change-role');
    Route::post('user/change-password/{user}', [UserController::class, 'changePassword'])->name('user.change-password');
    
    Route::get('report-tickets', [ReportController::class, 'reportTickets'])->name('report.tickets');
    Route::post('report-tickets/export', [ReportController::class, 'exportTickets'])->name('report.export.tickets');
    Route::get('report-store', [ReportController::class, 'reportStore'])->name('report.store');
    Route::post('report-store/export', [ReportController::class, 'exportStore'])->name('report.export.store');

    Route::resource('log-activities', LogActivityController::class)->only(['index', 'destroy']);
});

Route::get('customer-display/{type}', [Controller::class, 'customer_display'])->name('customer.display');
Route::get('product-display/{name}/{price}', [ProductController::class, 'display_product'])->name('product.display');

resources/views/layout/main.blade.php
<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>{{ config('app.name') }}</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    @stack('prepend-style')
    @include('layout.style')
    @stack('addons-style')
</head>

<body>
    <div class="loader"></div>
    <div class="main-wrapper main-wrapper-1">
        <div class="navbar-bg"></div>
        <nav class="navbar navbar-expand-lg main-navbar sticky">
            <div class="form-inline mr-auto">
                <ul class="navbar-nav">
                    <li>
                        <a href="#" data-toggle="sidebar" class="nav-link nav-link-lg collapse-btn"> 
                            <i data-feather="align-justify"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link nav-link-lg fullscreen-btn">
                            <i data-feather="maximize"></i>
                        </a>
                    </li>
                    <li style="display: flex;align-items: center;">
                        <div class="search-element">
                            <h5 class="mb-0 mt-1 ml-2 text-secondary" style="font-size:1.1rem">
                                @yield('title')
                            </h5>
                        </div>
                    </li>
                </ul>
            </div>
            <ul class="navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                        <span style="font-size:16px" class="mr-2">Hello, {{ auth()->user()->name }}</span> 
                        <img alt="image" src="{{ asset('assets/img/user.png') }}" class="user-img-radious-style"> 
                        <span class="d-sm-none d-lg-inline-block"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right pullDown">
                        <div class="dropdown-title">Hello {{ auth()->user()->getRoleNames()->first() }}</div>
                        {{-- <a href="#" class="dropdown-item has-icon" onclick="changePassword({{ auth()->id() }})"> 
                            <i class="far fa-user"></i> Ganti Password
                        </a>  --}}
                        @can('view-activities')
                        <a href="{{ route('log-activities.index') }}" class="dropdown-item has-icon"> 
                            <i class="fas fa-bolt"></i> Aktifitas
                        </a> 
                        @endcan
                        <div class="dropdown-divider"></div>
                        <form action="{{ route('logout') }}" method="POST">
                            @csrf
                            <button class="dropdown-item has-icon text-danger" style="font-weight: 500;line-height: 1.2;font-size: 13px;" type="submit"> 
                                <i class="fas fa-sign-out-alt"></i>
                                Logout
                            </button>
                        </form>
                    </div>
                </li>
            </ul>
        </nav>
        <div class="main-sidebar sidebar-style-2">
            <aside id="sidebar-wrapper">
                <div class="sidebar-brand">
                <a href="{{ route('dashboard') }}" style="display: inline-flex;padding-top: 12px;padding-left: 6px;"> 
                    <img alt="image" src="{{ asset('assets/img/logo_main.png') }}" class="header-logo" style="height: 55px;" /> 
                    <div style="text-align: left;padding-top: 4px;padding-left: 8px;" id="name-apps">
                        <p style="text-transform: none;font-weight: 500;font-size: 13px;letter-spacing: 0px;margin-bottom: 0px;">Sistem Informasi</p>
                        <p style="text-transform: none;font-weight: 700;font-size: 13px;letter-spacing: 0px;margin-bottom: 0px;line-height: 10px;">{{ config('app.name') }}</p>
                    </div>
                </a>
                </div>
                <ul class="sidebar-menu">
                    @include('layout.sidebar')
                </ul>
            </aside>
        </div>
        <!-- Main Content -->
        <div class="main-content">
            @yield('content')
        </div>
        <div id="notifications-state">
            @if (Session::get('status'))
                <span data-message="{{ Session::get('message') }}" data-status="{{ Session::get('status') }}"></span>
            @endif
        </div>
        <footer class="main-footer">
            <div class="footer-left">
                <a href="https://krakatio.com">Krakatio</a></a>
            </div>
            <div class="footer-right"></div>
        </footer>
    </div>

    @stack('prepend-script')
    @include('layout.script')
    <script>
        function clearError(form) {
            // if($(that).hasClass('shopping')){
            //     $(that).removeClass('shopping');
            //     alert( $(that).attr('class'));//btn btn-warning
            // }
            $('#'+form).find('.is-invalid').next().remove();
            $('#'+form).find('.is-invalid').removeClass('is-invalid');
            // .removeClass('is-invalid').next().remove();
            // $('#'+form+' textarea').removeClass('is-invalid').next().remove();
        }
    </script>
    @stack('addons-script')
</body>
<!-- index.html  21 Nov 2019 03:47:04 GMT -->
</html>

resources/views/layout/script.blade.php
<!-- General JS Scripts -->
<script src="{{ asset('assets/js/app.min.js') }}"></script>
<!-- JS Libraies -->
<!-- Page Specific JS File -->
<!-- Template JS File -->
<script src="{{ asset('assets/js/scripts.js') }}"></script>
<!-- Custom JS File -->
<script src="{{ asset('assets/js/custom.js') }}"></script>
<script src="{{ asset('assets/bundles/izitoast/js/iziToast.min.js') }}"></script>

<script>
    $('a.collapse-btn').click(function (e) {
        if (!$("body").hasClass("sidebar-mini")) { 
            $('#name-apps').hide()
        } else {
            $('#name-apps').show()
        }
    });

    setTimeout(() => {
        if( $('#notifications-state > *').length > 0 ) {
            let el = $('#notifications-state :first-child');
            let status = el.attr("data-status");
            let message = el.attr("data-message");
            
            if (status != 'error')
                showAlert('success', message, status);
            else 
                showAlert('error', message, 'error');
        }
    }, 500);

    function showAlert(status, message, title) {
        $data = {
            title: title,
            message: message,
            position: 'topRight'
        }

        if (status == 'success')
            iziToast.success($data)
        else 
            iziToast.error($data)
    }

    const formatRupiah = (money) => {
        return new Intl.NumberFormat('id-ID',
            { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }
        ).format(money);
    }

    const popupCenter = ({url, title, w, h}) => {
        // Fixes dual-screen position                             Most browsers      Firefox
        const dualScreenLeft = window.screenLeft !==  undefined ? window.screenLeft : window.screenX;
        const dualScreenTop = window.screenTop !==  undefined   ? window.screenTop  : window.screenY;

        const width = window.innerWidth ? window.innerWidth : document.documentElement.clientWidth ? document.documentElement.clientWidth : screen.width;
        const height = window.innerHeight ? window.innerHeight : document.documentElement.clientHeight ? document.documentElement.clientHeight : screen.height;

        const systemZoom = width / window.screen.availWidth;
        const left = (width - w) / 2 / systemZoom + dualScreenLeft
        const top = (height - h) / 2 / systemZoom + dualScreenTop
        const newWindow = window.open(url, title, 
        `
        scrollbars=yes,
        width=${w / systemZoom}, 
        height=${h / systemZoom}, 
        top=${top}, 
        left=${left}
        `
        )

        if (window.focus) newWindow.focus();
    }
</script>

resources/views/layout/sidebar.blade.php
<li class="menu-header">Menu Navigasi</li>

@role('owner')
<li class="dropdown {{ request()->is('dashboard-ticket') ? 'active' : '' }}">
    <a href="{{ route('dashboard.ticket') }}" class="nav-link"><i class="fas fa-desktop"></i><span>Dashboard Tiket</span></a>
</li>
<li class="dropdown {{ request()->is('dashboard-store') ? 'active' : '' }}">
    <a href="{{ route('dashboard.store') }}" class="nav-link"><i class="fas fa-desktop"></i><span>Dashboard Store Produk</span></a>
</li>
@endrole
@hasanyrole('pos|ticket')
<li class="dropdown {{ request()->is('dashboard') ? 'active' : '' }}">
    <a href="{{ route('dashboard') }}" class="nav-link"><i class="fas fa-desktop"></i><span>Dashboard</span></a>
</li>
@endhasanyrole  

@can('view-tickets')
<li class="menu-header">Data Menu Tiket</li> {{-- Menu Tiket --}}

<li class="dropdown {{ request()->is('tickets*') ? 'active' : '' }}">
    <a href="#" class="menu-toggle nav-link has-dropdown" style="padding-left: 16px;"><i class="fas fa-ticket-alt"></i><span>Tiket</span></a>
    <ul class="dropdown-menu">
        <li class="{{ request()->is('tickets-valid') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('ticket.valid') }}">Valid</a>
        </li>
        <li class="{{ request()->is('tickets-invalid') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('ticket.invalid') }}">Invalid</a>
        </li>
    </ul>
</li>
@endcan

@can('view-sale-tickets')
<li class="dropdown {{ request()->is('ticket-sales*') ? 'active' : '' }}">
    <a href="{{ route('ticket-sales.index') }}" class="nav-link"><i class="fas fa-shopping-basket"></i><span>Penjualan Tiket</span></a>
</li>
@endcan

@can('view-sale-products')
<li class="menu-header">Data Menu Store</li>  {{-- Menu Produk --}}
@endcan

{{-- <li class="dropdown {{ request()->is('products*') ? 'active' : '' }}">
    <a href="#" class="menu-toggle nav-link has-dropdown">
        <i data-feather="grid"></i>
        <span>Produk</span>
    </a>
    <ul class="dropdown-menu"> 
        <li class="{{ request()->is('products*') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('products.index') }}">Produk Saya</a>
        </li>
        <li class="{{ request()->is('product-all') ? 'active' : '' }}">
            <a class="nav-link" href="#">Seluruh Produk</a>
        </li>
    </ul>
</li> --}}

@can('view-products')
<li class="dropdown {{ request()->is('products*') ? 'active' : '' }}">
    <a href="{{ route('products.index') }}" class="nav-link"><i class="fas fa-cube"></i><span>Produk</span></a>
</li>
@endcan

{{-- <li class="dropdown {{ request()->is('transaction') ? 'active' : '' }}">
    <a href="{{ route('transaction.index') }}" class="nav-link"><i data-feather="calendar"></i><span>Transaksi Baru</span></a>
</li> --}}

@can('view-sale-products')
<li class="dropdown {{ request()->is('transaction*') ? 'active' : '' }}">
    <a href="{{ route('transaction.index') }}" class="nav-link"><i class="fas fa-boxes"></i><span>Transaksi Baru</span></a>
</li>
@endcan

@can('view-sale-products')
<li class="dropdown {{ request()->is('product-sales*') ? 'active' : '' }}">
    <a href="{{ route('product-sales.index') }}" class="nav-link"><i class="fas fa-shopping-cart"></i><span>Penjualan Produk</span></a>
</li>
@endcan

@can('view-users')
<li class="menu-header">Menu Admin</li> {{-- Menu Tiket --}}
@endcan

@can('view-users')
<li class="dropdown {{ request()->is('users*') ? 'active' : '' }}">
    <a href="{{ route('users.index') }}" class="nav-link"><i class="fas fa-id-badge"></i><span>Manajemen Akun</span></a>
</li>
<li class="dropdown {{ request()->is('report-tickets') ? 'active' : '' }}">
    <a href="{{ route('report.tickets') }}" class="nav-link"><i class="fas fa-file-alt"></i><span>Laporan Sistem Tiket</span></a>
</li>
<li class="dropdown {{ request()->is('report-store') ? 'active' : '' }}">
    <a href="{{ route('report.store') }}" class="nav-link"><i class="fas fa-file-contract"></i><span>Laporan POS Store</span></a>
</li>
@endcan

{{-- <li class="dropdown {{ request()->is('category*') ? 'active' : '' }}">
    <a href="#" class="nav-link"><i data-feather="calendar"></i><span>Laporan</span></a>
</li> --}}

@can('view-users')
<li class="dropdown {{ request()->is('log-activities') ? 'active' : '' }}">
    <a href="{{ route('log-activities.index') }}" class="nav-link"><i class="fas fa-clipboard-list"></i><span>Aktivitas Petugas</span></a>
</li>
@endcan

resources/views/layout/style.blade.php
<!-- General CSS Files -->
<link rel="stylesheet" href="{{ asset('assets/css/app.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/bundles/izitoast/css/iziToast.min.css') }}">
<!-- Template CSS -->
<link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/components.css') }}">
<!-- Custom style CSS -->
<link rel="stylesheet" href="{{ asset('assets/css/custom.css') }}">
<link rel='shortcut icon' type='image/x-icon' href="{{ asset('assets/img/favicon.ico') }}" />